-- Field MVP schema (empty — no seed data)
-- Source: docs/database-design.md

BEGIN;

CREATE TABLE users (
  id uuid PRIMARY KEY,
  display_name varchar(255) NOT NULL,
  email varchar(255) UNIQUE,
  phone varchar(50),
  role varchar(50) NOT NULL,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE addresses (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  street_line varchar(500) NOT NULL,
  building varchar(255),
  notes text,
  latitude numeric(10, 7),
  longitude numeric(10, 7),
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX addresses_lat_lng_idx ON addresses (latitude, longitude);

CREATE TABLE recipients (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(255) NOT NULL,
  phone varchar(50),
  default_address_id bigint REFERENCES addresses (id),
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE recipient_emails (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  recipient_id bigint NOT NULL REFERENCES recipients (id),
  email varchar(255) NOT NULL,
  is_primary boolean NOT NULL DEFAULT false,
  UNIQUE (recipient_id, email)
);

CREATE TYPE task_type AS ENUM (
  'Delivery',
  'Install',
  'Removal',
  'Site Survey',
  'Other'
);

CREATE TYPE task_status AS ENUM (
  'Created',
  'Unassigned',
  'Assigned',
  'Loaded',
  'Arrived',
  'Completed',
  'Failed'
);

CREATE TABLE task_types (
  id smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code varchar(50) NOT NULL UNIQUE,
  name varchar(100) NOT NULL,
  sort_order smallint NOT NULL DEFAULT 0
);

CREATE TABLE task_statuses (
  id smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code varchar(50) NOT NULL UNIQUE,
  name varchar(100) NOT NULL,
  sort_order smallint NOT NULL DEFAULT 0,
  is_terminal boolean NOT NULL DEFAULT false
);

CREATE TABLE task_status_transitions (
  from_status_id smallint NOT NULL REFERENCES task_statuses (id),
  to_status_id smallint NOT NULL REFERENCES task_statuses (id),
  PRIMARY KEY (from_status_id, to_status_id)
);

CREATE TABLE tasks (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  task_type task_type NOT NULL,
  status task_status NOT NULL,
  description text,
  external_key varchar(100),
  created_by_user_id uuid NOT NULL REFERENCES users (id),
  recipient_id bigint REFERENCES recipients (id),
  destination_address_id bigint REFERENCES addresses (id),
  crew_size smallint,
  estimated_hours numeric(5, 2),
  is_time_specific boolean NOT NULL DEFAULT false,
  can_start_early boolean NOT NULL DEFAULT false,
  window_start_at timestamptz,
  window_end_at timestamptz,
  completed_notes text,
  completed_at timestamptz,
  failed_reason text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT tasks_window_range_chk CHECK (
    window_end_at IS NULL
    OR window_start_at IS NULL
    OR window_end_at >= window_start_at
  )
);

CREATE INDEX tasks_status_window_idx ON tasks (status, window_start_at, window_end_at);
CREATE INDEX tasks_recipient_id_idx ON tasks (recipient_id);
CREATE INDEX tasks_external_key_idx ON tasks (external_key) WHERE external_key IS NOT NULL;
CREATE INDEX tasks_created_at_idx ON tasks (created_at DESC);

-- Many crew members per task (API/form: crewMemberIds: string[])
CREATE TABLE task_crew_members (
  task_id bigint NOT NULL REFERENCES tasks (id) ON DELETE CASCADE,
  user_id uuid NOT NULL REFERENCES users (id),
  PRIMARY KEY (task_id, user_id)
);

CREATE INDEX task_crew_members_user_idx ON task_crew_members (user_id);

CREATE TABLE task_attachments (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  task_id bigint NOT NULL REFERENCES tasks (id),
  uploaded_by_user_id uuid NOT NULL REFERENCES users (id),
  kind varchar(50) NOT NULL,
  storage_key varchar(500) NOT NULL,
  mime_type varchar(100) NOT NULL,
  file_name varchar(255),
  file_size_bytes bigint,
  caption text,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX task_attachments_task_created_idx ON task_attachments (task_id, created_at);

CREATE TABLE task_documents (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  task_id bigint NOT NULL REFERENCES tasks (id),
  kind varchar(50) NOT NULL,
  storage_key varchar(500) NOT NULL,
  file_name varchar(255) NOT NULL,
  generated_at timestamptz NOT NULL,
  generated_by_user_id uuid REFERENCES users (id),
  UNIQUE (task_id, kind)
);

CREATE INDEX task_documents_task_kind_idx ON task_documents (task_id, kind);

CREATE TABLE email_deliveries (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  task_id bigint NOT NULL REFERENCES tasks (id),
  "trigger" varchar(50) NOT NULL,
  to_addresses text NOT NULL,
  subject varchar(500) NOT NULL,
  status varchar(50) NOT NULL,
  provider_message_id varchar(255),
  error_message text,
  sent_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX email_deliveries_task_created_idx ON email_deliveries (task_id, created_at);
CREATE INDEX email_deliveries_pending_idx ON email_deliveries (status) WHERE status = 'pending';

CREATE TABLE task_status_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  task_id bigint NOT NULL REFERENCES tasks (id),
  from_status_id smallint REFERENCES task_statuses (id),
  to_status_id smallint NOT NULL REFERENCES task_statuses (id),
  changed_by_user_id uuid REFERENCES users (id),
  notes text,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX task_status_events_task_created_idx ON task_status_events (task_id, created_at);

COMMIT;
