-- Per-crew start/end check-in logs (time + optional GPS).
-- Task status: Arrived on first Start; Completed when all starters have Ended.

BEGIN;

CREATE TABLE IF NOT EXISTS task_crew_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  task_id bigint NOT NULL REFERENCES tasks (id),
  user_id uuid NOT NULL REFERENCES users (id),
  event_type varchar(20) NOT NULL CHECK (event_type IN ('started', 'ended')),
  latitude numeric(10, 7),
  longitude numeric(10, 7),
  accuracy_meters numeric(8, 2),
  recorded_at timestamptz NOT NULL DEFAULT now(),
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (task_id, user_id, event_type)
);

CREATE INDEX IF NOT EXISTS task_crew_events_task_idx
  ON task_crew_events (task_id, recorded_at);

COMMIT;
