-- Per-user completion / failed notes (one row per user per task).
-- Crew ends and admin status changes upsert here so later writers do not overwrite others.

BEGIN;

CREATE TABLE IF NOT EXISTS task_completion_notes (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  task_id bigint NOT NULL REFERENCES tasks (id) ON DELETE CASCADE,
  user_id uuid NOT NULL REFERENCES users (id),
  outcome varchar(20) NOT NULL CHECK (outcome IN ('Completed', 'Failed')),
  notes text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (task_id, user_id)
);

CREATE INDEX IF NOT EXISTS task_completion_notes_task_idx
  ON task_completion_notes (task_id, created_at);

-- Backfill from legacy single-author fields when we know who wrote them.
INSERT INTO task_completion_notes (task_id, user_id, outcome, notes, created_at, updated_at)
SELECT
  t.id,
  t.completion_notes_by_user_id,
  CASE
    WHEN t.status = 'Failed' OR (t.failed_reason IS NOT NULL AND t.completed_notes IS NULL)
      THEN 'Failed'
    ELSE 'Completed'
  END,
  COALESCE(NULLIF(trim(t.failed_reason), ''), NULLIF(trim(t.completed_notes), '')),
  COALESCE(t.completed_at, t.updated_at, now()),
  now()
FROM tasks t
WHERE t.completion_notes_by_user_id IS NOT NULL
  AND (
    NULLIF(trim(t.failed_reason), '') IS NOT NULL
    OR NULLIF(trim(t.completed_notes), '') IS NOT NULL
    OR t.status IN ('Completed', 'Failed')
  )
ON CONFLICT (task_id, user_id) DO NOTHING;

COMMIT;
