-- Append-only task history for status transitions (and other explicit audit events).
-- Crew start/end, attachments, emails, and documents are read from their source tables.

BEGIN;

CREATE TABLE IF NOT EXISTS task_history_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  task_id bigint NOT NULL REFERENCES tasks (id),
  event_type varchar(50) NOT NULL,
  actor_user_id uuid REFERENCES users (id),
  from_status task_status,
  to_status task_status,
  summary text,
  recorded_at timestamptz NOT NULL DEFAULT now(),
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS task_history_events_task_recorded_idx
  ON task_history_events (task_id, recorded_at DESC, id DESC);

COMMIT;
